server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /auth/ {
        proxy_pass https://auth-service.gentlewave-5817ead5.spaincentral.azurecontainerapps.io/;
        proxy_set_header Host auth-service.gentlewave-5817ead5.spaincentral.azurecontainerapps.io;
        proxy_ssl_server_name on;
    }

    location /posts {
        proxy_pass https://post-service.gentlewave-5817ead5.spaincentral.azurecontainerapps.io;
        proxy_set_header Host post-service.gentlewave-5817ead5.spaincentral.azurecontainerapps.io;
        proxy_ssl_server_name on;
    }
}
