server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /auth/ {
        proxy_pass https://auth-service-1044319150113.europe-west1.run.app/;
        proxy_set_header Host auth-service-1044319150113.europe-west1.run.app;
        proxy_ssl_server_name on;
    }

    location /posts {
        proxy_pass https://post-service-1044319150113.europe-west1.run.app;
        proxy_set_header Host post-service-1044319150113.europe-west1.run.app;
        proxy_ssl_server_name on;
    }
}
